config/routes.rb
WebClientUi::Application.routes.draw do
  get "session/login"
  get "session/dashboard"
  get "session/users"
  get "session/billing"
  get "session/project_list"
  get "session/bundled_computes"
  get "session/load_balancers"
  get "session/accnt_owner"
  get "session/forget_password"
  get "session/sign_up"
  get "session/cloud_builder"
  get "session/volumes"

  root :to => 'session#login'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def login
    render :partial => '/session/login'
  end

  def dashboard
  end

  def projects
  end

  def users
  end

  def billing
  end

  def project_list
  end

  def bundled_computes
  end

  def load_balancers
  end

  def accnt_owner
  end
  
  def cloud_builder
  end
  
  def volumes
  end

  def forget_password
    render :partial => '/session/forget_password'
  end

  def sign_up
    render :partial => '/session/sign_up'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/layouts/_header.html.erb
<header class="l-head clearfix">
  <div class="avatar left clearfix"><i class="icon-user"></i></div>

  <dl class="user left">
    <dt><%= link_to 'Super SysAdmin Spoof', session_accnt_owner_path(), :id => 'accnt_owner' %></dt>
    <dd>CP System Default Account</dd>
  </dl>

  <p><a class="btn right" href="">Logout</a></p>
</header>

app/views/layouts/_navigation.html.erb
<nav class="span3 l-sidebar">
    <div class="logo"><img src="/assets/logo.png" alt="morphlabs"/></div>
    
    <ul class="main-nav">
        <li><%= link_to 'Dashboard', session_dashboard_path(), :id => 'dashboard' %></li>

        <li>
            <%= link_to 'Projects', session_project_list_path(), :id => 'projects' %>
        </li>

        <li><%= link_to 'Users', session_users_path(), :id => 'users' %></li>

        <li><%= link_to 'Usage', session_billing_path(), :id => 'billing' %></li>
        
        <li><%= link_to 'Support', session_billing_path(), :id => 'support' %></li>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>mCloud Web Client</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>

<!--[if lt IE 7]>
  <p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p>
<![endif]-->

<div class="container-fluid">
  <div class="row-fluid">

  <%= render "layouts/navigation" %>

    <div class="span9 l-main">

      <%= render "layouts/header" %>

          <%= yield %>

    </div>
  </div>
</div>
<%= javascript_include_tag "application" %>
</body>
</html>

app/views/session/_forget_password.html.erb
<h1>SET PASSWORD HERE</h1>

app/views/session/_login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>mCloud Web Client</title>

  <%= stylesheet_link_tag "application", :media => "all" %>

  <%= csrf_meta_tags %>
</head>
<body class="dark">

<!--[if lt IE 7]>
  <p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p>
<![endif]-->

<div class="l-main-content">
	<div class="login-container">
		<div class="logo"><img src="/assets/logo.png" alt="morphlabs"/></div>

		<form class="form-inline">
	        <input type="text" class="input-large" placeholder="Email">

	        <input type="password" class="input-large" placeholder="Password">

	        <%= link_to 'Login', session_dashboard_path(), :id => 'dashboard', :class => 'btn btn-primary btn-large' %>
	        <ul class="unstyled clearfix form-options">
		        <li class="left"><label class="checkbox"><input type="checkbox"> Keep Me Logged in</label></li>

		        <li class="left"><%= link_to 'Forgot Your Password', session_forget_password_path(), :id => 'forget_password' %></li>
	        </ul>
	    </form>

	    <p class="sign-up"><%= link_to "Don't have an Account? Sign Up Now!", session_sign_up_path(), :id => 'sign_up' %></p>
    </div>
</div>

<%= javascript_include_tag "application" %>
</body>
</html>

app/views/session/_sign_up.html.erb
<h1>SIGN-UP HERE</h1>

app/views/session/accnt_owner.html.erb
<div class="l-main-content">
    <form class="form-horizontal">
        <fieldset>
        	<legend>Your Information</legend>
        	
            <div class="control-group">
                <label class="control-label" for="name">Full Name</label>

                <div class="controls">
                    <input type="text" class="input-xlarge" id="name">
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="email">Email</label>

                <div class="controls">
                    <input type="text" class="input-xlarge" id="email">
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="email">SSH <em class="optional">(optional)</em></label>

                <div class="controls">
                    <textarea class="input-xlarge" id="textarea" rows="3">
</textarea>

                    <p class="help-block">Allow user to have SSH access to virtual machines</p>
                </div>
            </div>
        </fieldset>
        
        <fieldset>
        	<legend>Your Password</legend>
        	
            <div class="control-group">
                <label class="control-label" for="password">Password</label>

                <div class="controls">
                    <input type="text" class="input-medium" id="password">
                    
                    <p class="help-block">Must be at least 6 characters long</p>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="password-confirm">Password</label>

                <div class="controls">
                    <input type="text" class="input-medium" id="password-confirm">
                </div>
            </div>

        </fieldset>
        
        <fieldset>
        	<legend>Your Account Information</legend>
        	
            <div class="control-group">
                <label class="control-label" for="organization">Organization</label>

                <div class="controls">
                    <input type="text" class="input-xlarge" id="organization">
                    
                    <p class="help-block">The account's company name (ex. Spacely's Space Sprockets)</p>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="max-computes">Max Computes</label>

                <div class="controls">
                    <input type="number" class="input-small" id="max-computes">
                    
                    <p class="help-block">Maximum number of compute servers that this account can have</p>
                </div>
            </div>
            
             <div class="control-group">
                <label class="control-label" for="deactivate">Deactivate</label>

                <div class="controls">
                      <p class="help-block"><a href="">Deactivate your account.</a></p>
                </div>
            </div>
        </fieldset>
        
        <a href="#" class="btn btn-primary btn-horizontal">Save Changes</a>
    </form>
</div>

app/views/session/billing.html copy.erb
<style type="text/css">
	.table .empty-table {
		background-color: #F1f1f1;
		text-align: center;
		color: #AAA;
	}
</style>
<div class="l-main-content">
    <header class="clearfix">
        <h2 class="left">Billing Summary</h2>

        <p class="right"><a class="btn btn-primary disabled">Export</a></p>
    </header>

    <div class="filter" style="margin: 18px 0;">
        <select class="span4">
            <option>
                Select Project&hellip;
            </option>

            <option>
                Project 1
            </option>

            <option>
                3
            </option>

            <option>
                4
            </option>

            <option>
                5
            </option>
        </select> 
        
        <div class="right">
	        <select class="span2">
	            <option>
	                Month&hellip;
	            </option>
	
	            <option>
	                Jan
	            </option>
	
	            <option>
	                3
	            </option>
	
	            <option>
	                4
	            </option>
	
	            <option>
	                5
	            </option>
	        </select> 
	        
	        <select class="span2">
	            <option>
	                Year&hellip;
	            </option>
	
	            <option>
	                2012
	            </option>
	
	            <option>
	                3
	            </option>
	
	            <option>
	                4
	            </option>
	
	            <option>
	                5
	            </option>
	        </select>
        </div>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>Date</th>

                <th>Flavor</th>

                <th>Instance ID</th>

                <th class="align-right">Start Time</th>

                <th class="align-right">End Time</th>

                <th class="align-right">Usage</th>
            </tr>
        </thead>

        <tbody>
            <tr>
                <td colspan="6" class="empty-table">
               		Looks like no projects were selected, select one from the dropdown menu above.
                </td>
            </tr>
        </tbody>
        
        <!--
<tbody>
            <tr>
                <td>March 5, 2012</td>

                <td>m1.tiny</td>

                <td>test server</td>

                <td class="align-right">09:11:44 UTC</td>

                <td class="align-right">09:11:44 UTC</td>

                <td class="align-right">0.00 VM Hours</td>
            </tr>
        </tbody>
        
       
		<tfoot>
        	<tr>
        		<td colspan="5" class="align-right">Total Compute Usage</td>
        		
        		<td class="align-right">0.00 VM Hours</td>
        	</tr>
        </tfoot>
-->
    </table>
    
</div>

app/views/session/billing.html.erb
<div class="l-main-content">
    <header class="clearfix">
        <h2 class="left">Support</h2>
    </header>
    
    <p>At Morphlabs, our customers are very important to us and we have many different ways for you to connect with us.</p>

	<ul>
		<li><a href="">Look up an answer in the mCloud Knowledgebase</a></li>
		<li>Send us an email – <a href="">support@morphlabs.com</a></li>
		<li><a href="">Chat live with Morphlabs</a></li>
	</ul>
	
	<form>
                <fieldset>
                   <div class="control-group">
                        <label class="control-label" for="input01">First Name</label>

                        <div class="controls">
                            <input type="text" class="input-xlarge" id="input01">
                        </div>
                    </div>    
                    
                    <div class="control-group">
                        <label class="control-label" for="input01">Last Name</label>

                        <div class="controls">
                            <input type="text" class="input-xlarge" id="input01">
                        </div>
                    </div>    
                    
                    <div class="control-group">
                        <label class="control-label" for="input01">Company</label>

                        <div class="controls">
                            <input type="text" class="input-xlarge" id="input01">
                        </div>
                    </div>   
                    
                    <div class="control-group">
                        <label class="control-label" for="input01">Phone</label>

                        <div class="controls">
                            <input type="text" class="input-xlarge" id="input01">
                        </div>
                    </div>   
                    
                    <div class="control-group">
                        <label class="control-label" for="input01">Email Name</label>

                        <div class="controls">
                            <input type="text" class="input-xlarge" id="input01">
                        </div>
                    </div>   
                    
                    <div class="control-group">
                        <label class="control-label" for="input01">Description</label>

                        <div class="controls">
                           <textarea class="input-xlarge" id="textarea" rows="3"></textarea>
                        </div>
                    </div>            
            	</fieldset>
            </form>
</div>

app/views/session/bundled_computes.html.erb
<div class="l-main-content">
	<header class="clearfix">
        <h2 class="left">Bundled Computes</h2>

        <p class="right"><a class="btn btn-primary" data-toggle="modal" href="#myModal">Create Bunlde</a></p>
    </header>

    <ul class="table-list unstyled" id="bundled-list">
        <li class="clearfix thead">
        	<div class="status">
                &nbsp;
            </div>
        	
            <div class="name">
                Name
            </div>

            <div class="compute-size">
                Compute Size
            </div>

            <div class="category">
                Category
            </div>
            
            <div class="action align-right">
            	Action
            </div>
        </li>
        
        <li class="clearfix tbody">
            <div class="status">
                <div class="status left"><div class="current-status online"></div></div>
            </div>

            <div class="name">
                Bundled 1
            </div>

            <div class="compute-size">
                3000
            </div>

            <div class="category">
                category
            </div>
            
            <div class="action align-right">
            	<ul class="unstyled">
			        <li class="dropdown action-dropdown">
			        	<a href="#" class="default-action"><i class="icon-edit"></i> Edit</a>
			        	
			            <a class="dropdown-toggle" data-toggle="dropdown" rel="tooltip" title="More Options" href=""><b class="caret"></b></a>
			
			            <ul class="dropdown-menu">
			                <li><a href="#"><i class="icon-ban-circle"></i> Disable</a></li>
			
			                <li><a href="#"><i class="icon-user"></i> Make Owner</a></li>
			 
			                <li><a href="#"><i class="icon-trash"></i> Delete</a></li>
			            </ul>
			        </li>
			    </ul>
            </div>
        </li>
        
        <li class="clearfix tbody">
            <div class="status">
                <div class="status left"><div class="current-status online"></div></div>
            </div>

            <div class="name">
                Bundled 1
            </div>

            <div class="compute-size">
                3000
            </div>

            <div class="category">
                category
            </div>
            
            <div class="action align-right">
            	<ul class="unstyled">
			        <li class="dropdown action-dropdown">
			        	<a href="#" class="default-action"><i class="icon-edit"></i> Edit</a>
			        	
			            <a class="dropdown-toggle" data-toggle="dropdown" rel="tooltip" title="More Options" href=""><b class="caret"></b></a>
			
			            <ul class="dropdown-menu">
			                <li><a href="#"><i class="icon-ban-circle"></i> Disable</a></li>
			
			                <li><a href="#"><i class="icon-user"></i> Make Owner</a></li>
			 
			                <li><a href="#"><i class="icon-trash"></i> Delete</a></li>
			            </ul>
			        </li>
			    </ul>
            </div>
        </li>

        <li class="clearfix tbody">
            <div class="status">
                <div class="status left"><div class="current-status online"></div></div>
            </div>

            <div class="name">
                Bundled 1
            </div>

            <div class="compute-size">
                3000
            </div>

            <div class="category">
                category
            </div>
            
            <div class="action align-right">
            	<ul class="unstyled">
			        <li class="dropdown action-dropdown">
			        	<a href="#" class="default-action"><i class="icon-edit"></i> Edit</a>
			        	
			            <a class="dropdown-toggle" data-toggle="dropdown" rel="tooltip" title="More Options" href=""><b class="caret"></b></a>
			
			            <ul class="dropdown-menu">
			                <li><a href="#"><i class="icon-ban-circle"></i> Disable</a></li>
			
			                <li><a href="#"><i class="icon-user"></i> Make Owner</a></li>
			 
			                <li><a href="#"><i class="icon-trash"></i> Delete</a></li>
			            </ul>
			        </li>
			    </ul>
            </div>
        </li>
    </ul>
    
    <div class="pagination">
        <ul>
            <li><a href="#">Prev</a></li>

            <li class="active"><a href="#">1</a></li>

            <li><a href="#">2</a></li>

            <li><a href="#">3</a></li>

            <li><a href="#">4</a></li>

            <li><a href="#">Next</a></li>
        </ul>
    </div>
</div>

app/views/session/cloud_builder.html.erb
<style type="text/css">
.instance-wrapper {
    border-top: 1px solid #CCC;
    border-bottom: 1px solid #CCC;
}
.available-instance,
.selected-instance {
    height: 400px;
    overflow-y: auto;
}



.available-instance {
    width: 40%;
    float: left;
    border-right: 1px solid #CCC;
    background-color: #F5F5F5;
}

.selected-instance {
    width: 60%;
    float: right;
}

.instance-container {
	background-color: #FFF;
	border-bottom: 1px solid #CCC;
	position: relative;
}

.instance-container i {
	position: absolute; 
	top: 32px;
	right: 20px;
}

.instance-container:hover{ 
	cursor: pointer;
}

.available-instance .instance-container:hover i {
	right: 15px;
}

dd {
    margin-left: 0;
}

dl {
	padding: 0 15px;
}

.info {
	width: 100%;
	background-color: #F1f1f1;
	padding: 9px 0;
	box-shadow: inset 0 3px 5px rgba(0,0,0,.1);
	font-size: 12px;
	/* display: none; */
}

.info dl {
	margin: 3px 0;
}

.info dt {
	float: left;
	font-weight: normal;
	width: 50px;
	color: #aaa;
	margin-right: 10px;
	text-align: right;
}

.instance dt {
	font-size: 16px;
	font-family: 'TitilliumText22LRegular', sans-serif;
}

.instance dd {
	color: #CCC;
	margin-bottom: 3px;
}

.builder-header h2 {
	margin-bottom: 3px;
}

.builder-header h2:hover,
.description:hover {
	background-color: #fcf6e4;
}

.description {
	color: #666;
}

dd a {
	background-color: #333;
	color: #FFF;
	font-size: 11px;
	text-transform: uppercase;
	padding: 1px 3px;
}

.red {
	color: red;
}




</style>

<div class="l-main-content">
    <header class="builder-header">
        <h2>Click to edit project name<span class="red">*</span></h2>
  		<!-- <input type="text" class="span3"> -->
  		
  		<p class="description">Click to edit Description<span class="red">*</span></p>
  		<!-- <textarea class="input-xlarge" id="textarea" rows="3"></textarea> -->
    </header>

    <div class="instance-wrapper clearfix">
        <div class="available-instance">
            <div class="instance-container clearfix">
            	<i class="icon-arrow-right right"></i>
                
                <dl class="left instance">
                    <dt>TTY</dt>

                    <dd>m1.tiny</dd>
                    
                    <dd><a href="#">Show Details</a></dd>
                </dl>
                
                <div class="info clearfix left">
                	<dl>
                		<dt>CPU</dt>
                	           			
                	    <dd>Core i7</dd>
                	</dl>
                	
                	<dl>
                		<dt>Storage</dt>
                	           			
                	    <dd>180 Gb</dd>
                	</dl>
                	
                	<dl>
                		<dt>RAM</dt>
                	           			
                	    <dd>3GB</dd>
                	</dl>
                </div>
            </div>
            
            <div class="instance-container clearfix">
            	<i class="icon-arrow-right right"></i>
                
                <dl class="left instance">
                    <dt>TTY</dt>

                    <dd>m1.medium</dd>
                    
                    <dd><a href="#">Show Details</a></dd>
                </dl>
                
                <div class="info clearfix left">
                	<dl>
                		<dt>CPU</dt>
                	           			
                	    <dd>Core i7</dd>
                	</dl>
                	
                	<dl>
                		<dt>Storage</dt>
                	           			
                	    <dd>180 Gb</dd>
                	</dl>
                	
                	<dl>
                		<dt>RAM</dt>
                	           			
                	    <dd>3GB</dd>
                	</dl>
                </div>
            </div>
            
            <div class="instance-container clearfix">
            	<i class="icon-arrow-right right"></i>
                
                <dl class="left instance">
                    <dt>TTY</dt>

                    <dd>m1.large</dd>
                    
                    <dd><a href="#">Show Details</a></dd>
                </dl>
                
                <div class="info clearfix left">
                	<dl>
                		<dt>CPU</dt>
                	           			
                	    <dd>Core i7</dd>
                	</dl>
                	
                	<dl>
                		<dt>Storage</dt>
                	           			
                	    <dd>180 Gb</dd>
                	</dl>
                	
                	<dl>
                		<dt>RAM</dt>
                	           			
                	    <dd>3GB</dd>
                	</dl>
                </div>
            </div>
        </div>

        <div class="selected-instance">
            <div class="instance-container clearfix">
            	<i class="icon-remove right"></i>
                
                <dl class="left instance">
                    <dt>TTY</dt>

                    <dd>m1.large</dd>
                    
                    <dd><a href="#">Show Details</a></dd>
                </dl>
                
                <div class="info clearfix left">
                	<dl>
                		<dt>CPU</dt>
                	           			
                	    <dd>Core i7</dd>
                	</dl>
                	
                	<dl>
                		<dt>Storage</dt>
                	           			
                	    <dd>180 Gb</dd>
                	</dl>
                	
                	<dl>
                		<dt>RAM</dt>
                	           			
                	    <dd>3GB</dd>
                	</dl>
                </div>
            </div>
        </div>
    </div>

<div class="form-actions">
	<button type="submit" class="btn btn-primary">Save changes</button>
	<button class="btn">Cancel</button>
</div>
</div>

app/views/session/dashboard.html.erb
<div class="l-main-content">
  <div id="holder"></div>
  <div id="holder2"></div>
  <div id="holder3"></div>
</div>

app/views/session/load_balancers.html.erb
<div class="l-main-content">
	<header class="clearfix">
        <h2 class="left">Load Balancer</h2>

        <p class="right"><a class="btn btn-primary" data-toggle="modal" href="#myModal">Creat Load Balancer</a></p>
    </header>

    <ul class="table-list unstyled" id="load-list">
        <li class="clearfix thead">
        	<div class="status">
                &nbsp;
            </div>
        	
            <div class="name">
                Name
            </div>

            <div class="ipaddress">
                IP Address
            </div>

            <div class="port align-right">
                Port
            </div>
            
            <div class="action align-right">
            	Action
            </div>
        </li>

        <li class="clearfix tbody">
            <div class="status">
                <div class="current-status online"></div>
            </div>

            <div class="name">
                sysadmin@example.com
            </div>

            <div class="ipaddress">
                IP Address
            </div>
            
            <div class="port align-right">
                58
            </div>
            
            <div class="action align-right">
            	<ul class="unstyled">
			        <li class="dropdown action-dropdown">
			        	<a href="#" class="default-action"><i class="icon-edit"></i> Edit</a>
			        	
			            <a class="dropdown-toggle" data-toggle="dropdown" rel="tooltip" title="More Options" href=""><b class="caret"></b></a>
			
			            <ul class="dropdown-menu">
			                <li><a href="#"><i class="icon-ban-circle"></i> Disable</a></li>
			
			                <li><a href="#"><i class="icon-user"></i> Make Owner</a></li>
			 
			                <li><a href="#"><i class="icon-trash"></i> Delete</a></li>
			            </ul>
			        </li>
			    </ul>
            </div>
        </li>
        
        <li class="clearfix tbody">
            <div class="status">
                <div class="current-status online"></div>
            </div>

            <div class="name">
                sysadmin@example.com
            </div>

            <div class="ipaddress">
                IP Address
            </div>
            
            <div class="port align-right">
                58
            </div>
            
            <div class="action align-right">
            	<ul class="unstyled">
			        <li class="dropdown action-dropdown">
			        	<a href="#" class="default-action"><i class="icon-edit"></i> Edit</a>
			        	
			            <a class="dropdown-toggle" data-toggle="dropdown" rel="tooltip" title="More Options" href=""><b class="caret"></b></a>
			
			            <ul class="dropdown-menu">
			                <li><a href="#"><i class="icon-ban-circle"></i> Disable</a></li>
			
			                <li><a href="#"><i class="icon-user"></i> Make Owner</a></li>
			 
			                <li><a href="#"><i class="icon-trash"></i> Delete</a></li>
			            </ul>
			        </li>
			    </ul>
            </div>
        </li>
        
        <li class="clearfix tbody">
            <div class="status">
                <div class="current-status online"></div>
            </div>

            <div class="name">
                sysadmin@example.com
            </div>

            <div class="ipaddress">
                IP Address
            </div>
            
            <div class="port align-right">
                58
            </div>
            
            <div class="action align-right">
            	<ul class="unstyled">
			        <li class="dropdown action-dropdown">
			        	<a href="#" class="default-action"><i class="icon-edit"></i> Edit</a>
			        	
			            <a class="dropdown-toggle" data-toggle="dropdown" rel="tooltip" title="More Options" href=""><b class="caret"></b></a>
			
			            <ul class="dropdown-menu">
			                <li><a href="#"><i class="icon-ban-circle"></i> Disable</a></li>
			
			                <li><a href="#"><i class="icon-user"></i> Make Owner</a></li>
			 
			                <li><a href="#"><i class="icon-trash"></i> Delete</a></li>
			            </ul>
			        </li>
			    </ul>
            </div>
        </li>
    </ul>
    
    <div class="pagination">
        <ul>
            <li><a href="#">Prev</a></li>

            <li class="active"><a href="#">1</a></li>

            <li><a href="#">2</a></li>

            <li><a href="#">3</a></li>

            <li><a href="#">4</a></li>

            <li><a href="#">Next</a></li>
        </ul>
    </div>
</div>